# COLEGIO ADA BYRON - Configuración del Servidor
server.port=8080
spring.application.name=matricula-adabyron

# BASE DE DATOS POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5433/adabyron_db
spring.datasource.username=postgres
spring.datasource.password=45013195
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# JWT CONFIGURACION
app.jwt.secret=adaByronSecretKey2026SuperSeguroParaJWTTokenAuthentication
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200


# LOGGING
logging.level.com.adabyron=INFO
logging.level.org.springframework.security=WARN
logging.file.name=logs/adabyron.log

# Configuracion de subida de archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
app.upload.dir=uploads
